### ISSUE TITLE
Line separated array list is not parsed properly by ktmpl

### ISSUE THREAD

**Issue by suneeta-mall** [InQuicker/ktmpl#20]
In this template:
```
kind: "Template"
apiVersion: "v1"
metadata:
  name: "xx"
  annotations:
    description: "ss"
labels:
  template: "ss"
objects:
  - kind: Job
    apiVersion: batch/v1
    metadata:
      name: metadata-generation
      namespace: sp
    spec:
      template:
        metadata:
          name: somepod
        spec:
          containers:
          - name: metadata-generation-container
            image: some-image
            args: ["x", 
                  "generate"]       
parameters:
  - name: "REGION"
    description: "AWS region name"
    required: true
    parameterType: "string"
 ```

because of line sperated arg list, ktmpl fails to apply them variable and convert the yaml with variables. If I put the list in one line it works fine.

**Comment by jimmycuadra** [comment]
This may be an issue with the upstream YAML parser that ktmpl uses. I'll need to look into this a bit more to verify.

**Comment by suneeta-mall** [comment]
Sure. Just wanted to add that the list syntax - seems to work fine.
```
        spec:
          containers:
            - name: some-container
              image: blah blah
              args: 
                - "run"
                - "--cluster"
```
