### ISSUE TITLE
Octal values not preserved

### ISSUE THREAD

**Issue by JonathanBroomeMYOB** [InQuicker/ktmpl#22]
As part of my config I have the following:
```
volumes:
- name: init-script
  configMap:
    name: app-init-script
    defaultMode: 0744
```

But when run through ktmpl this comes out as:
```
volumes:
- name: init-script
  configMap:
    name: app-init-script
    defaultMode: 744
```

The `744` is then considered to be an int, rather than an octal value, so the app fails to deploy.
As a workaround, I can set this to 484, which is the base 10 equivalent of 744.
