### ISSUE TITLE
Multiple YAML documents cannot be present

### ISSUE THREAD

**Issue by apobbati** [InQuicker/ktmpl#9]
Is it intentional that the tool cannot handle multiple YAML documents in a single file like below?

``` yaml
# frontend.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          image: "$(GROUP)/$(IMAGE_NAME):$(IMAGE_VERSION)"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: frontend
```

When I run the following, this is what I get:

``` bash
> ktmpl frontend.yaml \
  --parameter GROUP myorg \
  --parameter IMAGE_NAME myimage \
  --parameter IMAGE_VERSION latest

Error: Only one YAML document can be present in the template.
```
